# Generated by Django 4.2.4 on 2023-08-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('end_date', models.DateField()),
                ('prize_pool', models.PositiveIntegerField()),
                ('trophy', models.ImageField(upload_to='')),
                ('location', models.CharField(blank=True, default='online', max_length=60)),
                ('teams', models.ManyToManyField(related_name='event', to='teams.team')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trophy', to='teams.team')),
            ],
        ),
    ]
