# Generated by Django 4.2.4 on 2023-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('nickname', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('age', models.PositiveIntegerField(blank=True)),
                ('nation', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[(1, 'Top Laner'), (2, 'Jungler'), (3, 'Mid Laner'), (4, 'Bot Laner'), (5, 'Support'), (6, 'COACH')], max_length=20)),
                ('retired', models.BooleanField()),
            ],
        ),
    ]
