# Generated by Django 4.2.4 on 2023-08-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.IntegerField(choices=[(1, 'Top Laner'), (2, 'Jungler'), (3, 'Mid Laner'), (4, 'Bot Laner'), (5, 'Support'), (6, 'Coach')], max_length=20),
        ),
    ]
