# Generated by Django 4.2.4 on 2023-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='')),
                ('region', models.CharField(max_length=25)),
                ('active_players', models.ManyToManyField(related_name='team', to='players.player')),
                ('substitution', models.ManyToManyField(related_name='sub', to='players.player')),
            ],
        ),
    ]
